//BUSINESSOWNER
export const BUSINESSOWNER_ADD = "BUSINESSOWNER_ADD";
//CATEGORY
export const CATEGORY_ADD = "CATEGORY_ADD";
export const CATEGORY_GET = "CATEGORY_GET";
export const CATEGORIES_GET = "CATEGORIES_GET";
//USER
export const USER_ADD = "USER_ADD";
//GIFT
export const GIFT_GET = "GIFT_GET";
//GREETINGCARD
export const GREETINGCARD_ADD = "GREETINGCARD_ADD";
export const GREETINGCATRD_GET = "GREETINGCARD_GET";

// export const COURSES_SAVED = "COURSES_SAVED";
// export const COURSE_DELETED = "COURSE_DELETED";
// export const COURSE_UPDATED = "COURSE_UPDATED";
// export const MESSAGE_SET = "MESSAGE_SET";
// export const MESSAGE_REMOVED = "MESSAGE_REMOVED";